### ISSUE TITLE
TRIBITS_ALLOW_MISSING_EXTERNAL_PACKAGES prints extraneous warnings

### ISSUE THREAD

**Issue by kddevin** [TriBITSPub/TriBITS#80] opened 2015-08-03 18:06 UTC
A Trilinos customer reports that extraneous Tribits warnings are causing failures in his CDASH dashboard.

TRIBITS_ALLOW_MISSING_EXTERNAL_PACKAGES prints warnings if the package is not found; e.g., 
WARNING: SCORECgmi is being ignored since its directory is missing and SCORECgmi_ALLOW_MISSING_EXTERNAL_PACKAGE = TRUE!
However, the user is not trying to enable SCOREC or any part of it, so this warning is irrelevant.

It would be better if these messages were printed ONLY if a user actually enabled a missing package  either explicitly or through dependencies (and, in fact, CMake should probably fail in these cases).  With the current Tribits system, almost all Trilinos users will see these warnings.

**Comment by lefebvre** [comment] 2015-08-03 18:15
Agreed! SCALE receives over a dozen of these about Trilinos packages.
The irritant is made worse by the new cdash recognizing these as formal
configure warnings. Which in hind sight I don't know why the older cdash
didn't recognize them.

**Comment by bartlettroscoe** [comment] 2015-08-04 15:16
The problem is how to alert the developer or user when they attempt to provide an optional package but misspell it or something.  For example, suppose someone tried to provide the `SCOREC` packages by cloning the `SCOREC repo` by cloned it lower case:

    `Trilinos/scorec/`

The user might think they provided the package and if you remove the warnings, the only indication they would get is that the package would not show up in the enable list.

I see a few possible options:

1) Turn off warnings about missing packages in release mode and make release mode the default for all builds.  Only turn on development mode explicitly.  In release mode, the variable ` ${PROJECT_NAME}_ASSERT_MISSING_PACKAGES` is set to `FALSE` and no warnings about any missing packages are given. The problem with this is that if developers forget to turn on development mode, the will not see any strong compiler warnings.  So, scratch that.

2) Turn off these warnings by default in all modes by default but add a new option `${PROJECT_NAME}_WARN_ABOUT_MISSING_EXTERNAL_PACKAGES` that will bring the warnings back.  This would aid in debugging efforts

My guess is that option-2 is likely the best solution.

Below is an email about this same issue.

----

**Comment by ibaned** [comment] 2015-08-04 15:26
I think Roscoe's option 2, only printing such warnings
when we are trying to figure out why a package isn't here,
would be sufficient.
For the specific case in question, these are packages
which most Trilinos users do not have, and so they
are now getting warnings by default.
The defaults (and their current configurations) should
result in these packages being silently ignored,
with additional options as necessary to enable
these warnings for the few that do use those packages.

**Comment by bartlettroscoe** [comment] 2015-08-04 17:38
Okay, I will implement:

2) Turn off these warnings by default in all modes by default but add a new option ${PROJECT_NAME}_WARN_ABOUT_MISSING_EXTERNAL_PACKAGES that will bring the warnings back.

The biggest job will be updating all of the unit tests that pin down behavior.

**Comment by bartlettroscoe** [comment] 2015-08-05 01:13
@lefebvre, I suspect that newer versions of CDash are flagging all "WARNING" strings in the CMake output as warnings.  Therefore, I think we need to change a lot of the using of "WARNING" in TriBITS to "NOTE" to avoid this.

**Comment by bartlettroscoe** [comment] 2015-08-05 14:28
So here is some output related to missing external/inserted packages that I would argue should say.  

Currently, for example, in CASL VERA you see:

```
WARNING: Drekar is being ignored since its directory is missing and Drekar_ALLOW_MISSING_EXTERNAL_PACKAGE = TRUE!
WARNING: Setting VERA_ENABLE_VRIPSSdrekar=OFF because Drekar is a required missing package!
```

The first line giving the warning:
```
WARNING: Drekar is being ignored since its directory is missing and Drekar_ALLOW_MISSING_EXTERNAL_PACKAGE = TRUE!
```
would disappear by default with the changes I am making, fine.

However, I would argue that the second line should stay, but `WARNING` should be changed to `NOTE` and the output should be changed to:
```
NOTE: Setting VERA_ENABLE_VRIPSSdrekar=OFF because package VRIPSSdrekar has required dependency on missing package Drekar!
```
Otherwise, the downstream package (`VRIPSSdrekar` in this case) would get silently disabled and it would not be clear why.  That would violate the rule [TriBITS prints all enables and disables to stdout](https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-prints-all-enables-and-disables-to-stdout).

Any objections?

**Comment by ibaned** [comment] 2015-08-05 14:33
makes sense, changing WARNING to NOTE is a good solution for things that still should print.

**Comment by lefebvre** [comment] 2015-08-05 15:00
I agree. Notification should be given to the user and "Note" instead of
"Warning" will resolve dashboard noise.

**Comment by bartlettroscoe** [comment] 2015-08-05 19:42
I pushed the two commits shown in the TriBITS #80 Issue to the github repo and I snapshotted TriBITS to Trilinos 'master' in the commit:

```
commit b9526c841385acd4edd2b97bf60a0e0babf38290
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Wed Aug 5 13:36:17 2015 -0400

    Automatic snapshot commit from tribits at c567878
    
    Origin repo remote tracking branch: 'origin/master'
    Origin repo remote repo URL: 'origin = git@github.com:TriBITSPub/TriBITS'
    
    At commit:
    
    commit effcd6873739e302fb156fbea5635d4cb3980bc8
    Author:  Roscoe A. Bartlett <bartlettra@ornl.gov>
    Date:    Wed Aug 5 10:54:20 2015 -0400
    Summary: Remove warnings/notes about missing external packages by default (TriBITS #80)
    ...

M       cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake
M       cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake
M       cmake/tribits/core/package_arch/TribitsProcessPackagesAndDirsLists.cmake
M       cmake/tribits/doc/build_ref/TribitsBuildReferenceBody.rst
M       cmake/tribits/doc/developers_guide/TribitsDevelopersGuide.rst
```

This was also pushed to the CASL git repo for TriBITS so for SCALE to get it, it just needs to pull from git@casl-dev:TriBITS.

Documentation is updated at:

   https://tribits.org/doc/TribitsDevelopersGuide.html
   https://tribits.org/doc/TribitsBuildReference.html

Now, when you configure Trilinos 'master' by default, you get:

```
Processing Project, Repository, and Package dependency files and building internal dependencies graph ...

-- Trilinos_NUM_SE_PACKAGES='147'
-- Tentatively enabling TPL 'Pthread'
```

However, when you configure with `Trilinos_WARN_ABOUT_MISSING_EXTERNAL_PACKAGES=TRUE` you get:

```
Processing Project, Repository, and Package dependency files and building internal dependencies graph ...

NOTE: SCORECgmi is being ignored since its directory is missing and SCORECgmi_ALLOW_MISSING_EXTERNAL_PACKAGE = TRUE!
NOTE: SCORECpcu is being ignored since its directory is missing and SCORECpcu_ALLOW_MISSING_EXTERNAL_PACKAGE = TRUE!
NOTE: SCORECapf is being ignored since its directory is missing and SCORECapf_ALLOW_MISSING_EXTERNAL_PACKAGE = TRUE!
NOTE: SCORECmds is being ignored since its directory is missing and SCORECmds_ALLOW_MISSING_EXTERNAL_PACKAGE = TRUE!
NOTE: SCORECparma is being ignored since its directory is missing and SCORECparma_ALLOW_MISSING_EXTERNAL_PACKAGE = TRUE!
NOTE: SCORECgmi is being ignored since its directory is missing and SCORECgmi_ALLOW_MISSING_EXTERNAL_PACKAGE = TRUE!
NOTE: SCORECpcu is being ignored since its directory is missing and SCORECpcu_ALLOW_MISSING_EXTERNAL_PACKAGE = TRUE!
NOTE: SCORECapf is being ignored since its directory is missing and SCORECapf_ALLOW_MISSING_EXTERNAL_PACKAGE = TRUE!
NOTE: SCORECmds is being ignored since its directory is missing and SCORECmds_ALLOW_MISSING_EXTERNAL_PACKAGE = TRUE!
NOTE: SCORECparma is being ignored since its directory is missing and SCORECparma_ALLOW_MISSING_EXTERNAL_PACKAGE = TRUE!
-- Trilinos_NUM_SE_PACKAGES='147'
-- Tentatively enabling TPL 'Pthread'
```

With all the unit testing, documentation, repo operations, testing, ticket updates, etc. this was more than 3 hours of work, for changing about about 6 lines of code :-(.

I am closing as complete.  However, if you see other problems, please let me know.

**Closed by bartlettroscoe** 2015-08-05 19:42 UTC
Labels: enhancement
