### ISSUE TITLE
"public domain" is not a license

### ISSUE THREAD

**Issue by nschloe** [TriBITSPub/TriBITS#223] opened 2017-09-13 13:27 UTC
A boring legal issue: The file `tribits/win_interface/include/winmath.h` contains code that is marked as

> public domain rewrite of acosh(3), asinh(3) and atanh(3)

No copyright holder is specified. If something is marked "public domain", one can mostly assume that this is based on the mix-up with the term "open-source". _Public domain_ means the absence of copyright, and whoever wrote the code has to take legal action to disclaim it. I've never seen this happening.

@bartlettroscoe, did you write that? If yes, I'd strongly suggest to remove the term "public domain" and specify a license.

More info on this matter:
 * https://www.gnu.org/philosophy/categories.en.html
 * https://opensource.org/node/878

**Comment by bartlettroscoe** [comment] 2017-09-13 14:11
@nschloe,

Thanks for the heads-up. I think was written by Bill Hoffman at Kitware under the contract with SNL way back in 2008.  Really this stuff is just needed for Trilinos and it should be factored out of TriBITS and moved back into Trilinos proper.  Everything in win_interface should actually just go into Trilinos.  It was creates so that some Trilinos packages that used non-standard headers could port to Windows.  I will create a backlog issue to move this entire directory out of TriBITS and put it back into Trilinos.

**Comment by bartlettroscoe** [comment] 2017-09-13 14:45
I created #224 to move this out of TriBITS.

@nschloe, is this a major blocker for anything?  This code was in Trilinos releases going back to 2008 and this code passed several "open source" checking tools, including at ORNL labs as part of CASL VERA.  In fact, a private company was contracted to search all of the source code for CASL VERA, which included all of Trilinos and TriBITS.  The only code that was found to have some license issues was some code in Dakota.

Because of that level of analysis, I don't think there are really any license problem with this code (at least , or that process would have likely flagged it.  But it will still be good to get this out of TriBITS just because I don't think it needs to be there and is not general enough for TriBITS.

**Comment by nschloe** [comment] 2017-09-13 14:58
>  is this a major blocker for anything?

Not yet. Debian reviews have gotten stricter recently with unlicensed files though, and after I've had to adapt some packages, I thought I go ahead and make sure to reduce this kind of friction in the future. One instance included files which had the copyright declared, but not the license, so I would assume that `tribits/win_interface/include/winmath.h` with no stated copyright and a non-license will be subject to critique. (The fact that the previous reviews didn't catch this is probably due to it being small.)

**Comment by bartlettroscoe** [comment] 2019-01-19 16:17
Closing as a duplicate of #224.

**Closed by bartlettroscoe** 2019-01-19 16:17 UTC
