### ISSUE TITLE
TIMEOUT in Wrong Place Causes Problems

### ISSUE THREAD

**Issue by jmgate** [TriBITSPub/TriBITS#257] opened 2018-04-18 20:42 UTC
The Charon team uncovered some odd behavior yesterday.  At some point, someone added a `TIMEOUT` to one of our tests, but they accidentally did so inside one of the `TEST_<idx>` blocks.  The developer's guide specifies

> TIMEOUT <maxSeconds>
> 
> If passed in, gives maximum number of seconds the test will be allowed to run before being timed-out and killed (see Setting timeouts for tests (`TRIBITS_ADD_TEST()`)). This is for the full CTest test, not individual `TEST_<idx>`commands!

but I guess that wasn't seen at the time.  As with all things, this test was copied and pasted a number of times, so the problem propagated.

The observed behavior in these cases, though, is apparently `ctest` will run all the `TEST_<idx>` tests, but the overall success or failure is not aggregated correctly.  We're not sure if it's:
*  the test that included the `TIMEOUT` passed, so the advanced test was considered successful, or
*  it doesn't matter which tests pass/fail, as the result will always be success.

In these particular cases, `TEST_0` is copying stuff to the appropriate directory, `TEST_1` runs Charon, which completes successfully, some more tests run, and eventually `TEST_X` runs an `exodiff`.  The `exodiff` tests were failing (and have been for a long time it seems), but the overall test result, the one submitted to CDash, is a pass.

We've changed all our tests such that `TIMEOUT` now appears in the right place, but it seems this behavior should be dealt with.

**Comment by bartlettroscoe** [comment] 2018-04-18 22:09
Yea, this is type of problem that occurs when intermingling "overall" inside of the `TEST_<IDX>` blocks.  To catch problems like this we need to refactor how parsing in the `TRIBITS_ADD_ADVANCED_TEST()` function is done as per #136.

For now, the advise I would give is to carefully inspect the generated test driver files as described in:

* https://tribits.org/doc/TribitsDevelopersGuide.html#debugging-and-examining-test-generation-tribits-add-advanced-test

**Comment by bartlettroscoe** [comment] 2019-01-19 16:09
As I stated [above](https://github.com/TriBITSPub/TriBITS/issues/257#issuecomment-382545128) This is not really a bug, but a lack of error checking.  This will be addressed as part of #136.  Closing as a duplicate of #136.

**Closed by bartlettroscoe** 2019-01-19 16:09 UTC
Labels: component: core, resolution: duplicate, type: question
