### ISSUE TITLE
FAIL_REGULAR_EXPRESSION does not work

### ISSUE THREAD

**Issue by kddevin** [TriBITSPub/TriBITS#85] opened 2015-09-24 15:36 UTC
**Next Action Status:**

Clean tested fix pushed to TriBITS GitHub 'master' and snapshotted to Trilinos 'develop' (see [below](https://github.com/TriBITSPub/TriBITS/issues/85#issuecomment-258867969)).  Next: Final manual review or just close?

**Description:**

FAIL_REGULAR_EXPRESSION does not work with TRIBITS_ADD_EXECUTABLE_AND_TEST.
Ross suggested separate TRIBITS_ADD_EXECUTABLE/TRIBITS_ADD_TEST to work
around the problem, but the behavior is the same (i.e., the test prints
fail but ctest reports that it passes).

I wrote the following program in testfail.cpp:
```
# include <iostream>

int main()
{
  std::cout << "FAIL" << std::endl;
}

I added the following text to CMakeLists.txt:

TRIBITS_ADD_EXECUTABLE_AND_TEST(
   testfail
   SOURCES ${HEADERS} testfail.cpp
   FAIL_REGULAR_EXPRESSION "FAIL"
   COMM serial mpi
)
```

I expect the test to fail when I run "make test".  But it does not:

```
Start 74: Zoltan2_testfail_MPI_4
74/84 Test #74: Zoltan2_testfail_MPI_4 ..................................
Passed    0.36 sec
```

The relevant lines of CTestTestfile.cmake are below:
```
add_test(Zoltan2_testfail_MPI_4 "/usr/lib64/openmpi/bin/mpiexec" "-np" "4"
"/home/kddevin/code/Trilinos_repo/Obj_zoltan2/packages/zoltan2/test/driver/
Zoltan2_testfail.exe")
set_tests_properties(Zoltan2_testfail_MPI_4 PROPERTIES
FAIL_REGULAR_EXPRESSION "The following Teuchos::RCPNode objects were
created" LABELS "Zoltan2" PROCESSORS "4" REQUIRED_FILES
"/home/kddevin/code/Trilinos_repo/Obj_zoltan2/packages/zoltan2/test/driver/
Zoltan2_testfail.exe")
---
```

With separate TRIBITS_ADD_EXECUTABLE/TRIBITS_ADD_TEST:

```
TRIBITS_ADD_EXECUTABLE(
testfail
SOURCES testfail.cpp
COMM serial mpi
)

TRIBITS_ADD_TEST(
testfail
NAME testfailTest
FAIL_REGULAR_EXPRESSION "FAIL"
COMM serial mpi
)
```

From CTestTestfile.cmake:
```
add_test(Zoltan2_testfailTest_MPI_4 "/usr/lib64/openmpi/bin/mpiexec" "-np" "4" "/home/kddevin/code/Trilinos_repo/Obj_zoltan2/packages/zoltan2/test/driver/Zoltan2_testfail.exe")
set_tests_properties(Zoltan2_testfailTest_MPI_4 PROPERTIES FAIL_REGULAR_EXPRESSION "The following Teuchos::RCPNode objects were created" LABELS "Zoltan2" PROCESSORS "4" REQUIRED_FILES "/home/kddevin/code/Trilinos_repo/Obj_zoltan2/packages/zoltan2/test/driver/Zoltan2_testfail.exe")
```

**Comment by bartlettroscoe** [comment] 2015-09-24 19:21
The problem is the hidden overwriting of the property `FAIL_REGULAR_EXPRESSION` with:

```
FAIL_REGULAR_EXPRESSION "The following Teuchos::RCPNode objects were
created"
```

This is a hidden, undocumented feature of TriBITS that really should not even be in TriBITS since it is specific to Trilinos/Teuchos.  At the very least, it should be a plugin feature.

For now, I will add a unit test that will demonstrate the desired behavior and resolve the conflict with this default check for RCP leaks.

As a workaround for now, disable the RCP check by passing in `DISABLE_CIRCULAR_REF_DETECTION_FAILURE` to `TRIBITS_PACKAGE()` as described [here](https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-package-decl) or if you only want to turn this off for the specific test, set the **local** CMake variables:

```
    SET(${PACKAGE_NAME}_ENABLE_CIRCULAR_REF_DETECTION_FAILURE OFF)
    SET(${PROJECT_NAME}_ENABLE_CIRCULAR_REF_DETECTION_FAILURE OFF)
```
and it should respect your setting of `FAIL_REGULAR_EXPRESSION`.  Basically, I am going to make it so that the user-supplied `FAIL_REGULAR_EXPRESSION` disables the detection of dangling RCP nodes.  But since `FAIL_REGULAR_EXPRESSION` is pretty rare, that is not loosing very much.

**Comment by kddevin** [comment] 2015-09-24 19:50
Thanks, Ross.
Let me make sure I understand.  After the fix, if I specify
FAIL_REGULAR_EXPRESSION "FAIL;Teuchos::RCPNode"
I would catch failures reported by the test and RCPNode failures, right?
If this is correct, I will specify both strings in our CMakeLists.txt and we'll be good to go without losing any error checking.
Thanks for your prompt attention to this bug.
Karen

**Comment by bartlettroscoe** [comment] 2015-09-24 20:12
The question is what should the behavior be?  Would you rather that the user-specified FAIL_REGULAR_EXPRESSION be added to the default list?  That is, if you specify:

```
    FAIL_REGULAR_EXPRESSION  FAIL
```
and dangling RCP node detection is turned on, would you want to have the property set as:

```
FAIL_REGULAR_EXPRESSION "FAIL;The following Teuchos::RCPNode objects were
created"
```

?

I guess that seems reasonable.

**Comment by kddevin** [comment] 2015-09-24 22:12
Yes, concatenating the default string with the user's string would be great if it is possible.  Thank you!
If it isn't possible, we can specify both in CMakeLists.txt.

**Comment by kddevin** [comment] 2015-10-15 20:29
The following diff fixes this bug.  Should I commit it directly in Trilinos' Tribits, or do you need to apply it in github and then transfer it to Trilinos?
There were two bugs:  
-The wrong variables were checked when setting FAIL_REGEX_STRINGS, so concatenation was never happening.
-When passing ARGN to set_tests_properties, CMake broke regular expressions with multiple parts (e.g., "FAIL;BUMMER") into separate arguments.  This bug may be tested separately by specifying a regex like "FAIL;BUMMER" for FAIL_REGULAR_EXPRESSION in a test's CMakeLists.txt file.
Karen

$ diff TribitsAddTestHelpers.cmake TribitsAddTestHelpers.cmake.fixed
58c58
<     SET_TESTS_PROPERTIES(${ARGN})
---
>     SET_TESTS_PROPERTIES(${ARGV0} ${ARGV1} ${ARGV2} "${ARGV3}")
594,595d593
<   SET(FAIL_REGEX_STRINGS "")
< 
597c595
<     IF (FAIL_REGEX_STR)
---
>     IF (FAIL_REGEX_STRINGS)
609c607
<     IF (FAIL_REGEX_STR)
---
>     IF (FAIL_REGEX_STRINGS)
625c623
< # Set the timeout for a test already aded
---
> # Set the timeout for a test already added

**Comment by kddevin** [comment] 2015-10-15 20:37
OK; I'm don't know why github reformatted my diff.  And it says I can't upload txt files.  So here's a screenshot.
![diff](https://cloud.githubusercontent.com/assets/9597421/10526803/32d7bfe6-734a-11e5-9ae0-513b16c3b07e.png)

**Comment by bartlettroscoe** [comment] 2015-10-20 21:56
Note the policies on [contributions to TriBITS](https://github.com/TriBITSPub/TriBITS/wiki/Contributing-to-TriBITS).  This is a pretty standard GitHub workflow and set of requirements for contributions but I figured it was necessary to make these clear for TriBITS.

I have it on my todo list to address this issue but for now the workarounds I have provided should be sufficient for your particular use cases till then.  Also note that you can just reset the CTest property `FAIL_REGULAR_EXPRESSION` yourself after adding the test as documented in the [TriBITS Developers Guide](https://tribits.org/doc/TribitsDevelopersGuide.html#setting-additional-test-properties-tribits-add-test).

**Comment by bartlettroscoe** [comment] 2015-10-23 02:43
Karen,

Changes committed directly to Trilinos/cmake/tribits/ and committed to the Trilinos `master` branch are no longer going to wiped out due to the snapshotting process.  See details [here](http://trac.trilinos.org/wiki/TriBITSTrilinosDev#trilinos_tribits_changes).

If you feel confident that this patch does not break the usage of TriBITS for Trilinos, go ahead and commit it.  But the burden falls on you if something goes wrong.  When I get time, I will add the automated tests and address this issue carefully and push and update the Trilinos snapshot.  Don't worry about conflicts,  They will be easy to address.

**Comment by bartlettroscoe** [comment] 2016-10-23 00:24
Sorry for the long delay, but commit 4303bea fixes this cleanly and adds good automated tests to demonstrate and protect correct behavior.

I will snapshot this into Trilinos proper once I get #126 finished.  I will run as much of the Trilinos test suite when I do.

**Comment by bartlettroscoe** [comment] 2016-11-07 15:33
The updated fix was snapshotted to the Trilinos GitHub 'develop' branch on Saturday, 11/5/2016 in the Trilinos commit:

```
commit f2b04f756935a55664f49d96aa24da3e4e688e70
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Fri Nov 4 15:34:03 2016 -0600

    Automatic snapshot commit from tribits at 4769da4
    
    Origin repo remote tracking branch: 'github/master'
    Origin repo remote repo URL: 'github = git@github.com:TriBITSPub/TriBITS.git'
    
    At commit:
    
    commit 4769da42b41ca12e295d829cd543d4c17a44417d
    Author:  Roscoe A. Bartlett <rabartl@sandia.gov>
    Date:    Thu Nov 3 07:36:18 2016 -0600
    Summary: Some edits after review from @ibaned (#126)
```

Which was merged to the Trilinos 'devleop' branch in the commit:

```
df19e9b "Merge branch 'tribits_github_snapshot' into develop"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Fri Nov 4 15:54:08 2016 -0600 (3 days ago)
```

To cleanly update Trilinos, I had to back out the earlier commit [c9f5e7bd](https://github.com/trilinos/Trilinos/commit/c9f5e7bd) that was made made directly to Trilinos to avoid a merge conflict.  That custom revert commit that I applied and pushed before the merge of the snapshot was:

```
commit 574e1cbc7ad7b06e7f756948812d9c97a31aafda
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Fri Nov 4 15:51:40 2016 -0600

    Revert c9f5e7bd 'Fixed Tribits ... FAIL_REGULAR_EXPRESSION'
    
    I have a clean fix for this in TriBITS proper and I need to revert this commit
    so that the updated fix merged in clean.

M       cmake/tribits/core/package_arch/TribitsAddTestHelpers.cmake
```

The revert as not straightforward because the changes to TriBITS were embedded in a commit that touched other Trilinos directories.  Therefore, I came up with a clean process for reverting just the change to TriBITS as part of another commit and I documented the process at the bottom of:

* http://trac.trilinos.org/wiki/TriBITSTrilinosDev#trilinos_tribits_changes

(see "Revert the change in Trilinos right before the next the TriBITS snapshot update:")

@kddevin, I added some pretty good automated tests that show that the `FAIL_REGULAR_EXPRESSION` argument works correctly for your use case.  But to be safe, you might want to just verify that for your usage in Trilinos.  Otherwise, I am okay with closing this.

**Comment by kddevin** [comment] 2016-11-09 21:57
I have tests of this capability in Zoltan2 (called "testfail"); they worked with the patch I put in Trilinos' TriBits.  If they are running OK with the new snapshot, then the new snapshot must be OK, too.  Thanks, @bartlettroscoe .

**Comment by bartlettroscoe** [comment] 2016-11-09 22:01
@kddevin, Thanks for thanks for taking the time to review this and sorry this took so long.

Closing as complete.

**Closed by bartlettroscoe** 2016-11-09 22:01 UTC
Labels: bug, in review
