### ISSUE TITLE
Enabling more Trilinos packages than necessary?

### ISSUE THREAD

**Issue by mhoemmen** [TriBITSPub/TriBITS#243] opened 2017-11-27 17:00 UTC
This issue mirrors https://github.com/trilinos/Trilinos/issues/2011 .
@bartgol

**Comment by bartgol** [comment] 2017-11-27 18:07
Thanks @mhoemmen  for redirecting me to the Tribits repo!

The issue is already explained in the linked issue in Trilinos. In short, some upstream packages are automatically enabled even if they are listed as required only for tests, and the tests are not currently enabled. This increases (for nothing) the compilation time. I would like (if possible) to enable such upstream packages only if tests are indeed enabled.

**Comment by bartlettroscoe** [comment] 2017-12-04 20:29
Sorry, this is a know defect (see #56).  I have a branch that fixes this (mentioned in #56)  but it will mean a lot of changes to Trilinos Dependencies.cmake files (and files in other TriBITS projects like many repos in CASL VERA).  We need to get #56 done.

**Comment by bartgol** [comment] 2017-12-04 21:29
@bartlettroscoe Ah, my bad, I didn't see that issue. Thanks for the info. Any thought on whether that branch will ever be merged, perhaps with a tentative timeline?

**Comment by bartlettroscoe** [comment] 2017-12-04 21:53
@bartgol,

> Any thought on whether that branch will ever be merged, perhaps with a tentative timeline?

Not sure at this point.  This is on my personal todo list but it is lower in the priority order.  It would help if other people complained as well (especially SNL management :-))

**Comment by bartgol** [comment] 2017-12-04 22:15
Ok, thanks for the update. =)

**Comment by mhoemmen** [comment] 2017-12-04 22:34
@rrdrake @prwolfe Is this an issue of importance to y'all?  If so, perhaps we could help Ross get more traction from management on this.

**Comment by bartlettroscoe** [comment] 2019-01-19 16:11
Closing as duplicate as per above.

**Closed by bartlettroscoe** 2019-01-19 16:11 UTC
